### ISSUE TITLE
The "Buffers" command not worked ?

### ISSUE THREAD

**Issue by pilot513** [fisadev/fisa-vim-config#133] opened 2020-10-25 09:41 UTC
Hello.
When I try list buffers ":Buff" / ":Buffers" get error:
![fisa-Buffers-fault](https://user-images.githubusercontent.com/28645933/97103712-3f35ff00-16bf-11eb-89ef-3ddff17470a1.jpg)
The "Buffers" command not worked with your config anymore ?

**Comment by K-Dub1234** [comment] 2020-12-05 17:53
I don't think the issue is in the `:buff / :buffers` area, rather it seems it's in the list definition initially. 
Try redefining the list in question.

**Comment by fisadev** [comment] 2020-12-05 18:16
Hi!
This doesn't seem to be a problem with the config itself, but with the fzf plugin. Probably a bug in an older release, as it is working properly with the current version. Could you re-try with it? I'm closing the issue for now, because with the latest releases it can't be reproduced on my side. Feel free to re-open it if it happens again after upgrading the plugins.

**Closed by fisadev** 2020-12-05 18:16 UTC

**Comment by pilot513** [comment] 2020-12-06 07:21
@**fisadev** :  I checked it.  Indeed, with the updated version fzf is not reproduced.
Thanks!

**Comment by K-Dub1234** [comment] 2020-12-08 04:09
Ok awesome!
